config/routes.rb
Train::Application.routes.draw do

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
  end
  devise_for :users

  root 'static#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_validation do
    self.password_confirmation = self.password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    =render 'shared/head'

  %body
    =nav_bar responsive: true, inverse: true, fixed: :top, brand: "Train v1.0" do
      = menu_group do
        = menu_item "Home", root_path
        = menu_item "About Us", ''
        = menu_item "Contact", ''
      -if current_user
        = menu_group :pull => :right do
          = menu_item "Log Out", destroy_user_session_path
      -else
        = menu_group :pull => :right do
          = menu_item "Log In", sign_in_path
    .container
      .row
        .col-sm-9
          = bootstrap_flash
          .well
            = yield
        .col-sm-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    %nav.navbar.navbar-fixed-bottom.navbar-defaul.footer
      .container
        %p.text-muted.credit &copy; Company 2013

app/views/layouts/devise.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Train"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "devise", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "devise"


  %body
    .container
      .brand
        =link_to(image_tag('logo-default.png'), root_path)
      = bootstrap_flash
      = yield

    %nav.navbar.navbar-fixed-bottom.navbar-defaul.footer
      .container
        %p.text-muted.credit &copy; Company 2013

app/views/shared/_head.html.haml
%meta(charset="utf-8")
%meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%title= content_for?(:title) ? yield(:title) : "Train"
= csrf_meta_tags
/ Le HTML5 shim, for IE6-8 support of HTML elements
/[if lt IE 9]
  = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
= favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
= javascript_include_tag "application", "data-turbolinks-track" => true

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", sign_in_path(resource_name, format: nil), class: 'pull-left' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", sign_up_path(resource_name, format: nil), class: controller_name == 'passwords' ? 'pull-right' : 'pull-left' %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'pull-right' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>